# config.yaml
image: python:3.9
name: python_test
volumes:
  /Users/weiensong/data/code_project/easier-docker/example:
    bind: /path/to/container
    mode: rw
detach: true
command:
  - sh
  - -c
  - cd /path/to/container && python docker_example.py
